# -*- coding: utf-8 -*-
"""GUVI_chatbot_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139uuuBVG34dksuHcMIVa551i9ESYzVjP

# Final project - GUVI Multilingual GPT Chatbot
"""

!pip install transformers
!pip install torch
!pip install sentence-transformers
!pip install langchain
!pip install langchain-community
!pip install faiss-cpu

!pip install langdetect
!pip install deep-translator

!pip install streamlit pyngrok

from pyngrok import ngrok
ngrok.set_auth_token("30u56xSW1OXarvhpphlGjOLDba5_4XNvBZtLaNP4vsMfENoex")

from pyngrok import ngrok

# Kill any existing tunnels
ngrok.kill()

# Start Streamlit
get_ipython().system_raw('streamlit run app.py --server.port 8501 &')

# Open a tunnel on port 8501
public_url = ngrok.connect(8501)
print("👉 Your app is live here:", public_url)